config:
  experiment_name: "pca_horse"
  blocks: 
     # the module name of the visualized features (e.g. "output_block_4", "input_block_7").
    - "output_block_5"
    - "output_block_6"
    - "output_block_7"
    - "output_block_8"
    - "output_block_9"
    - "output_block_10"
    - "output_block_11"
  experiments_fit: # the list of the experiments to visualize the features for
    - "horse_in_mud"
  experiments_transform: # the list of the experiments used for calculating the principal components
    - "horse_in_mud"
