config:
  experiment_name: "cat_on_street_refine_sd"
  init_img: "/hdd/junyi/plug-and-play/experiments/cat_on_street/sd/swapped_image.png"
  ddim_steps: 999 # we use 999 steps for the best reconstruction
  save_feature_timesteps: 50