config:
  experiment_name: "sandwich_refine_512_sd" # name of the experiment, used for logging
  init_img: "/hdd3/junyi/odise/data/test_bench/Generated_low_res3500/000000000283_fuse/swapped_image.png" # path to the source image
  ddim_steps: 999 # we use 999 steps for the best reconstruction
  save_feature_timesteps: 50

prompts: # text prompts for translations
  - "a photo of an object, realistic, high resolution, high quality"

scale: 2 # unconditional guidance scale. Note that a higher value encourages deviation from the source image
num_ddim_sampling_steps: 50 # if left empty, defaults to the ddim_steps_callback arg used in the source experiment

# Control the level of structure preservation with injection timestep threshold
feature_injection_threshold: 40 # should be in [0, num_ddim_sampling_steps]

# Control the level of deviation from the source image with Negative prompting params.
negative_prompt: "unrealisitic, low resolution, low quality, unreal"
negative_prompt_alpha: 1.0 # ∈ [0, 1], determines the initial strength of negative-prompting (lower = stronger)
negative_prompt_schedule: "linear" # ∈ {"linear", "constant", "exp"}, determines the attenuation schedule of negative-prompting
# setting negative_prompt_alpha = 1.0, negative_prompt_schedule = "constant" is equivalent to not using negative prompting

# inverted image will be saved at 'experiment_name'/samples
# refined image will be saved at 'experiment_name'/translations//hdd3/junyi/pnp_swap/experiments/cat_on_grass1/translations/2_a_photo_of_a_cat
